#!/usr/bin/python
# -*- coding: utf-8 -*-

import MySQLdb
import os
import time
import sys
import pycurl
import threading
import ConfigParser
import fcntl
import signal
import lib
import random
from warnings import filterwarnings

class Threadpool():

    _workthreads = []
    _lastEctime = []
    _queue = []

    def __init__(self, poolsize, jobsize):
        self._poolsize = poolsize
        self._workthreads = []
        self._jobsize = jobsize

    def addjob(self, jobfunc, param):
        if len(Threadpool._queue) >= self._jobsize:
            lib.log('Task queue is full, drop current task', logfile)
            return
        Threadpool._queue.append((jobfunc, param))

    def start(self):
        for i in range(self._poolsize):
            wt = WorkThread()
            Threadpool._workthreads.append(wt)
            wt.start()

        wtt = WorkThreadTest()
        wtt.start()
        Threadpool._workthreads.append(wtt)

        mt = MonThread(mfrequence)
        mt.start()



    @staticmethod
    def callStaticFunc(func, param = {}):
        if not hasattr(Threadpool, func):
            lib.log("No such static func {func} in Threadpool".\
            format(func=func), logfile)
        return getattr(Threadpool, func)(**param)

    @staticmethod
    def getStatusTime():
        result = []
        for thread in Threadpool._workthreads:
            tid = thread.gettid()
            time = thread.getLastEctime()
            status = thread.getStatus()
            result.append((tid, time, status))
        return result

class MonThread(threading.Thread):

    def __init__(self, frequence):
        threading.Thread.__init__(self)
        self._frequence = frequence

    def run(self):
        while True:
            time.sleep(self._frequence)
            self.checkBlock()

    def checkBlock(self):
        sStatusTime = Threadpool.callStaticFunc("getStatusTime")
        now = int(time.time())
        results = []

        for sst in sStatusTime:
            tid, last, status = sst[0], sst[1], sst[2]
            diff = now - last
            if status == "running" and diff > timeout:
                result = "{tid} thread may block ,running time {s}(s)"\
                        .format(tid=tid, s=diff)
                results.append(result)

        if len(results) != 0:
            lib.log(",".join(results), logfile)

class WorkThreadTest(threading.Thread):

    def __init__(self):
        threading.Thread.__init__(self)
        self._timepos = int(time.time())
        self._status = "init"

    def run(self):
        while True:
            try:
                jobobj = Threadpool._queue.pop()
            except:
                self._status = "sleep"
                time.sleep(1)
                continue

            lib.log("test thread start!", logfile)
            self._status = "running"
            self.setEctime()

            jobobj[0](**jobobj[1])
            time.sleep(60)
            self._timepos = int(time.time())

    def gettid(self):
        return self.ident

    def setEctime(self):
        self._timepos = int(time.time())

    def getLastEctime(self):
        return self._timepos

    def getStatus(self):
        return self._status

    def sendMessage(self, msg):
        Threadpool.receive(msg, self.gettid())

    def exit(self):
        self.exit()
            
class WorkThread(threading.Thread):

    def __init__(self):
        threading.Thread.__init__(self)
        self._timepos = int(time.time())
        self._status = "init"

    def run(self):
        while True:
            try:
                jobobj = Threadpool._queue.pop()
            except:
                self._status = "sleep"
                time.sleep(1)
                continue

            self._status = "running"
            self.setEctime()

            jobobj[0](**jobobj[1])
            time.sleep(1)
            self._timepos = int(time.time())

    def gettid(self):
        return self.ident

    def setEctime(self):
        self._timepos = int(time.time())

    def getLastEctime(self):
        return self._timepos

    def getStatus(self):
        return self._status

    def sendMessage(self, msg):
        Threadpool.receive(msg, self.gettid())

    def exit(self):
        self.exit()

def h_sigterm(signum, frame):
    global quit
    quit = True

def do(func, params, repeat_times=0, doalert=True, span=1):
    time.sleep(span)
    repeat_times += 1
    error = ""
    ret = ""
    while repeat_times:
        repeat_times -= 1
        try:
            ret = func(**params)
        except Exception, e:
            error = e.args[0]
            continue
        break

    if error != "": 
        if repeat_times != 0:
            level = 2
        else:
            level = 1
        if doalert:
            call_hook_func("alert", {"msg": error, "level": level})
        return False
    return ret

def call_hook_func(funcname, param):
    func = getattr(hookmodule, funcname, None)
    if func:
        try:
            ret = func(**param)
        except Exception, e:
            lib.log("call hook function {funcname} failed: {error}"
            .format(funcname=funcname, error=str(e)), logfile)
    else:
        return False

def slave_change_master(slavedb, master_host, master_port, 
        master_logfile, master_logpos, master_user, master_password):
    cursor = slavedb.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute("stop slave;")
    cursor.execute("change master to master_host='{host}', master_user='{user}',\
master_password='{password}', master_port={port}, master_log_file='{logfile}', \
master_log_pos={logpos};".format(host=master_host, user=master_user, \
    password=master_password, port=master_port,logfile=master_logfile,\
    logpos=master_logpos))
    cursor.execute("start slave;")
    return True

def slave_become_master(slavedb):
    cursor = slavedb.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute("stop slave;")
    cursor.execute("reset master;")
    cursor.execute("show master status;")
    cursor.execute("set global read_only=0;")
    ret = cursor.fetchall()[0]
    master_logfile = ret["File"]
    master_logpos = ret["Position"]
    return (master_logfile, master_logpos)

def iosql_thread(slavedb, slaveinfo = ''):
    host = slaveinfo["host"] if "host" in slaveinfo["host"] else "none"
    port = slaveinfo["port"] if "port" in slaveinfo["port"] else "none"

    cursor = slavedb.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute("show slave status")
    ret = cursor.fetchall()[0]
    sqlt_status = ret["Slave_SQL_Running"]
    iot_status = ret["Slave_IO_Running"]
    if sqlt_status != "Yes":
        raise Exception("{host} {port} slave sql thread is not yes"\
              .format(host=host, port=port))
    if iot_status != "Yes":
        raise Exception("{host} {port} slave io thread is not yes"\
              .format(host=host, port=port))
    return True

def repl_delay(slavedb, slaveinfo = ''):
    host = slaveinfo["host"] if "host" in slaveinfo["host"] else "none"
    port = slaveinfo["port"] if "port" in slaveinfo["port"] else "none"

    cursor = slavedb.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute("show slave status")
    ret = cursor.fetchall()[0]
    read_master_log_pos = ret["Read_Master_Log_Pos"]
    exec_master_log_pos = ret["Exec_Master_Log_Pos"]

    if read_master_log_pos != exec_master_log_pos:
        raise Exception("{host} {port} slave delay"\
              .format(host=port, port=port))
    return exec_master_log_pos

def same_logfile(slavedb):
    cursor = slavedb.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute("show slave status")
    ret = cursor.fetchall()[0]
    master_log_file = ret["Master_Log_File"]
    relay_master_log_file = ret["Relay_Master_Log_File"]
    if master_log_file != relay_master_log_file:
        raise Exception("replay_master_log_file is not the same as master_log_file")
    return master_log_file

def change_master(slaves):
    setmaster = False
    curpos = 0

    for slave in slaves:
        # 1. connect to any slaves that belongs to the master
        slavedb = do(connect, slave, conrepeat, False, conrespan)
        if slavedb == False:
            continue
        # 2. check if it is the same logfile
        logfile = do(same_logfile, {"slavedb": slavedb}, replrepeat, 
            False, replrespan)
        if logfile == False:
            continue
        # 3. check if it is relay, give it 5 chances to be synced
        logpos = do(repl_delay, {"slavedb": slavedb}, replrepeat, 
            False, replrespan)
        if logpos == False:
            continue

        if not setmaster or curpos < logpos:
            setmaster = slave
            curpos = logpos
    if not setmaster:
        # disaster, no need to alert any more
        # raise Exception("None of the slaves can be raised as master") 
        return False
    bemasterdb = do(connect, setmaster, conrepeat, True, conrespan)
    master_logfile, master_logpos = do(slave_become_master, {"slavedb": bemasterdb})
    master_host, master_port = setmaster["host"], setmaster["port"]
    slaves.remove(setmaster)
    for slave in slaves:
        changeinfo = {
            "slavedb"        : do(connect, slave, conrepeat, True, conrespan),
            "master_host"    : master_host,
            "master_password": repluser,
            "master_user"    : replpass,
            "master_port"    : master_port,
            "master_logpos"  : master_logpos,
            "master_logfile" : master_logfile,
        }
        do(slave_change_master, changeinfo, 0, False)

def connect(host, user, passwd='', port='', **kargs):
    try:
        db = MySQLdb.connect(host=host, user=user, passwd=passwd, 
            port=port, connect_timeout=1)
    except Exception, e:
        raise Exception("{host} {port} {sql_err}"\
        .format(host=host, port=port, sql_err=e.args[1]))
    tglobal.dbconns.append(db)
    return db

def cleardb():
    while tglobal.dbconns:
        tglobal.dbconns.pop().close()

def slave_routine(slave):
    if "user" not in slave:
        slave["user"] = monuser
    if "passwd" not in slave:
        slave["passwd"] = monpass
    slavedb = do(connect, slave, conrepeat, True, conrespan)
    if slavedb == False:
        call_hook_func("slave_connect_error", {"slaveinfo": slave})
        return

    ret = do(iosql_thread, {"slavedb": slavedb, "slaveinfo": slave})
    if ret == False:
        call_hook_func("slave_thread_error", {"slaveinfo": slave})
        return

    ret = do(repl_delay, {"slavedb": slavedb, "slaveinfo": slave})
    if ret == False:
        call_hook_func("slave_delay", {"slaveinfo": slave})
        return

def master_routine(master):
    if "user" not in master:
        master["user"] = monuser
    if "passwd" not in master:
        master["passwd"] = monpass
    db = do(connect, master, conrepeat, True, conrespan)
    if not db and autochange:
        call_hook_func("master_connect_error", {"masterinfo": master})
        do(change_master, {"slaves": tglobal.suit["slaves"]})

def suit_routine(param):
    tglobal.suit = param
    master_routine(tglobal.suit["master"])
    for slave in tglobal.suit["slaves"]:
        slave_routine(slave)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "usage: mysqlmond [configfile]"
        sys.exit(1)

    if not os.path.isfile(sys.argv[1]):
        print "not a valid config file"
        sys.exit(1)

    config = ConfigParser.ConfigParser()
    config.read(sys.argv[1])

    pidfile     = config.get("log", "pid_file")
    logfile     = config.get("log", "log_file")

    frequency   = config.getfloat("monitor", "frequence")
    mhookmodule = config.get("monitor", "hook_module")
    repluser    = config.get("monitor", "repl_user")
    replpass    = config.get("monitor", "repl_pass")
    monuser     = config.get("monitor", "mon_user")
    monpass     = config.get("monitor", "mon_pass")
    conrepeat   = config.getint("monitor", "con_repeat")
    conrespan   = config.getfloat("monitor", "con_repeat_span")
    replrepeat  = config.getint("monitor", "rel_repeat")
    replrespan  = config.getfloat("monitor", "rel_repeat_span")
    autochange  = config.getint("monitor", "auto_change")
    mthreadnum  = config.getint("monitor", "max_thread_num")
    mtasknum    = config.getint("monitor", "max_task_num")
    mfrequence  = config.getfloat("monitor", "mon_frequence")
    timeout     = config.getfloat("monitor", "timeout")

    hookmodule = __import__(mhookmodule)
    if config.has_section(mhookmodule):
        for item in config.items(mhookmodule):
            setattr(hookmodule, item[0], item[1])

    if not getattr(hookmodule, "get_suit", None):
        print "There is no get_suit function in hook module"
        sys.exit(1)

    quit = False
 
    lib.fork_()
    os.setsid()
    lib.fork_(pidfile)

    fd = open(pidfile, "w")
    fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)

    filterwarnings('ignore', category = MySQLdb.Warning)
    tglobal = threading.local()
    thread_list = []

    lock = threading.RLock() 
    queue_pool = []

    tid = 0

    signal.signal(signal.SIGTERM, h_sigterm)

    tp = Threadpool(mthreadnum, mtasknum)
    tp.start()

    while True:
        time.sleep(frequency)
        if quit:
            lib.log("receiving kill signal, quit", logfile)
            exit(0)
        call_hook_func("before_monitor_started", {})
        suits = hookmodule.get_suit()
        for suit in suits:
            tp.addjob(suit_routine, {"param": suit})
        call_hook_func("after_monitor_ended", {"suits": suits})
